apiVersion: v1
appVersion: "v1.0.0"
description: Helm Chart to install ArvanCloud Webhook Issuer
name: arvancloud-webhook
version: 1.0.0
home: https://github.com/ParminCloud/arvancloud-certmanager-issuer/
sources:
  - https://github.com/ParminCloud/arvancloud-certmanager-issuer/
maintainers:
  - name: Muhammed Hussein Karimi
    url: https://karimi.dev
    email: info@karimi.dev
type: application
